language: node_js
node_js:
- 7.7.3
script: 
- yarn build
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- yarn install
services:
- docker
after_success:
- sudo docker build .