export const CREATE_ROOM = "CREATE_ROOM"
export const REMOVE_ROOM = "REMOVE_ROOM"
export const BOOK_ROOM = "BOOK_ROOM"
export const FINISH_ROOM = "FINISH_ROOM"
export const CANCEL_ROOM = "CANCEL_ROOM"